# Generated by Django 4.0.2 on 2022-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
